# Generated by Django 3.2.18 on 2023-07-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
    ]
