# Generated by Django 3.2.18 on 2023-11-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '书表'},
        ),
        migrations.AlterField(
            model_name='author',
            name='is_delete',
            field=models.BooleanField(choices=[(0, '未删除'), (1, '删除')], default=0),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='is_delete',
            field=models.BooleanField(choices=[(0, '未删除'), (1, '删除')], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_delete',
            field=models.BooleanField(choices=[(0, '未删除'), (1, '删除')], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=32, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='is_delete',
            field=models.BooleanField(choices=[(0, '未删除'), (1, '删除')], default=0),
        ),
    ]
